package com.qantica.soportando.model;
// Generated 12/03/2016 11:01:51 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Company generated by hbm2java
 */
public class Company  implements java.io.Serializable {


     private Integer companyId;
     private String name;
     private Set customers = new HashSet(0);

    public Company() {
    }

	
    public Company(String name) {
        this.name = name;
    }
    public Company(String name, Set customers) {
       this.name = name;
       this.customers = customers;
    }
   
    public Integer getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set customers) {
        this.customers = customers;
    }




}


