package com.qantica.soportando.model;
// Generated 12/03/2016 11:01:51 AM by Hibernate Tools 4.3.1



/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private Integer cid;
     private Company company;
     private User user;
     private String name;
     private String tel;

    public Customer() {
    }

	
    public Customer(Company company, User user, String name) {
        this.company = company;
        this.user = user;
        this.name = name;
    }
    public Customer(Company company, User user, String name, String tel) {
       this.company = company;
       this.user = user;
       this.name = name;
       this.tel = tel;
    }
   
    public Integer getCid() {
        return this.cid;
    }
    
    public void setCid(Integer cid) {
        this.cid = cid;
    }
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }




}


