package com.qantica.soportando.model;
// Generated 12/03/2016 11:01:51 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer uid;
     private String login;
     private String pass;
     private String email;
     private Date lastAccess;
     private int active;
     private String recoverCode;
     private Date recoverDue;
     private Set customers = new HashSet(0);

    public User() {
    }

	
    public User(String login, String pass, String email, int active) {
        this.login = login;
        this.pass = pass;
        this.email = email;
        this.active = active;
    }
    public User(String login, String pass, String email, Date lastAccess, int active, String recoverCode, Date recoverDue, Set customers) {
       this.login = login;
       this.pass = pass;
       this.email = email;
       this.lastAccess = lastAccess;
       this.active = active;
       this.recoverCode = recoverCode;
       this.recoverDue = recoverDue;
       this.customers = customers;
    }
   
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getLastAccess() {
        return this.lastAccess;
    }
    
    public void setLastAccess(Date lastAccess) {
        this.lastAccess = lastAccess;
    }
    public int getActive() {
        return this.active;
    }
    
    public void setActive(int active) {
        this.active = active;
    }
    public String getRecoverCode() {
        return this.recoverCode;
    }
    
    public void setRecoverCode(String recoverCode) {
        this.recoverCode = recoverCode;
    }
    public Date getRecoverDue() {
        return this.recoverDue;
    }
    
    public void setRecoverDue(Date recoverDue) {
        this.recoverDue = recoverDue;
    }
    public Set getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set customers) {
        this.customers = customers;
    }




}


